### ISSUE TITLE
NoneType: None

### ISSUE THREAD

**Issue by loicbramoulle** [strike-digital/asset_bridge#20]
Hi, I updated to 2.2.2, it worked fine. Then in a new blender (after a crash) I have this error whenever I click an asset:
NoneType: None
Thanks for any pointer, I tried hard reinstall, regenerating the library folder.

**Comment by strike-digital** [comment]
Hi, I've just released a new version, can you try it and see if the problem is fixed? Thanks!

**Comment by loicbramoulle** [comment]
**Hi, thanks!
So testing 2.2.3 in blender 2.6, I removed 2.2.2 first, and then when loading 2.2.3 I still had the repeating "NoneType: None" error.
And also this one:**
addon_utils.disable: asset_bridge not disabled
Modules Installed (asset_bridge) from 'G:\\Dropbox\\Blender_WORK\\ADDONs\\asset_bridge-2_2_3.zip' into 'C:\\Users\\Admin\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons'
Warning: This script was written Blender version 4.0.0 and might not function (correctly), though it is enabled

**and:**

File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\asset_bridge\settings.py", line 217, in get_asset_quality
NoneType: None
File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\asset_bridge\settings.py", line 197, in asset_quality_items
WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '0' matches no enum in 'AssetBridgeWmSettings', '', 'asset_quality'

**And so trying to drag & drop a material (all the assets thumbnails are still up to date.) Nothing happens, the material slot is still empty.

Then trying on the released 4.1, on instal I had a big error too:**

AttributeError: 'FileAssetSelectParams' object has no attribute 'asset_library_ref'. Did you mean: 'asset_library_reference'?
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\asset_wizard_pro\operators\update_local.py", line 51, in poll
    context.space_data.params.asset_library_ref == 'LOCAL' and \
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FileAssetSelectParams' object has no attribute 'asset_library_ref'. Did you mean: 'asset_library_reference'?


**BUT in 4.1 the materials are indeed downloaded and applied.
It just spams this error:**

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\asset_wizard_pro\operators\update_local.py", line 51, in poll
    context.space_data.params.asset_library_ref == 'LOCAL' and \
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FileAssetSelectParams' object has no attribute 'asset_library_ref'. Did you mean: 'asset_library_reference'?

Thanks !

**Comment by strike-digital** [comment]
Ah ok, there were a lot of big changes in the api between version 3.6 and 4.0, so the current addon won't work in versions earlier than 4.0. I should maybe add a check for that to warn people when they install it.

About installing it in 4.1, both of those errors seem to come from an addon called "asset_wizard_pro", rather than asset bridge (it looks like it hasn't been updated to support 4.0)

When you install it, is there an error that pops up in the UI? If there is, you could disable asset wizard first, as it looks like it's clogging up the terminal with a lot of errors, and then try and enable asset bridge, which should make it easier to find the correct error.

Thanks!

**Comment by loicbramoulle** [comment]
Ah thanks, I just updated Asset Wizzard and trying Bridge gives no error anymore in 4.1.
Just my catalogu (cat.txt file) are gone for some reason, maybe when I purged the folder, but odd that it didn't came back.

in 3.6 what is odd is that v 2.2.2 worked perfectly the first time I loaded a material, only next blender session it stopped working.
Just tried 2.1.0 and it doesn't load materials (Might be because of the recent change in AmbientCG website ? meaning Bridge cannot work in 3.6 with any version anymore maybe ?)

Thanks !
